"""Add name column to Hero model

Revision ID: 65f0a01d03b2
Revises: 25a5b75673ec
Create Date: 2023-10-12 00:25:45.573746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f0a01d03b2'
down_revision = '25a5b75673ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('super_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.drop_column('super_name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
